service: slack-delete-channel-history

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: python3.7
  stage: ops
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:*"
      Resource: "*"
  environment:
    TZ: 'Asia/Tokyo'
    SLACK_DELETE_CHANNEL_HISTORY_WEB_HOOK_URL: ${ssm:/slack-delete-channel-history/web-hook-url}
    SLACK_DELETE_CHANNEL_HISTORY_CHANNEL_NAME: ${ssm:/slack-delete-channel-history/channel-name}
    SLACK_DELETE_CHANNEL_HISTORY_ACCOUNT_NAME: ${ssm:/slack-delete-channel-history/account-name}
    MAX_DELETABLE_OBJECT_COUNT: 300

custom:
  pythonRequirements:
    dockerizePip: true

package:
  exclude:
    - './serverless/**'
    - './myvenv/**'
    - './node_modules/**'

functions:
  function:
    handler: src/slack_delete_channel_history.lambda_handler
    timeout: 900
    events:
      - schedule:
          name: 'slack-delete-channel-history'
          rate: cron(0 0 1 * ? *)
          enabled: true
          input:
            TARGET_CHANNEL: ${ssm:/slack-delete-channel-history/target-channel-name-1}
            EXPIRED_DATE: 365
