AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  SlackToken:
    Type: String
  SlackChannel:
    Type: String
  SlackCount:
    Type: Number

Resources:
  SlackDeleteChannelHistory:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: slack-delete-channel-history
      CodeUri: src/handlers
      Handler: slackDeleteChannelHistory.lambda_handler
      Runtime: python3.6
      Timeout: 900
      Events:
        MonthlyEvent:
          Type: Schedule
          Properties:
            Schedule: 'cron(0 0 1 * ? *)'
      Policies:
        - AWSLambdaExecute
        - CloudWatchLogsFullAccess
      Environment:
        Variables:
          TZ: 'Asia/Tokyo'
          SlackToken:
            Ref: SlackToken
          SlackChannel:
            Ref: SlackChannel
          SlackCount:
            Ref: SlackCount

