AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SlackChannel:
    Type: String
  SlackCount:
    Type: Number
  SlackToken:
    Type: String
Resources:
  SlackDeleteChannelHistory:
    Properties:
      CodeUri: s3://sam-sandbox-package/e9cb7d17ae32fa3f64fb998b4f4bd688
      Environment:
        Variables:
          SlackChannel:
            Ref: SlackChannel
          SlackCount:
            Ref: SlackCount
          SlackToken:
            Ref: SlackToken
          TZ: Asia/Tokyo
      Events:
        MonthlyEvent:
          Properties:
            Schedule: cron(0 0 1 * ? *)
          Type: Schedule
      FunctionName: slack-delete-channel-history
      Handler: slackDeleteChannelHistory.lambda_handler
      Policies:
      - AWSLambdaExecute
      - CloudWatchLogsFullAccess
      Runtime: python3.6
      Timeout: 900
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
